

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    # Keeps the container running so VS Code can attach to it
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      # Expose Streamlit port
      - "8510:8501"
      # Expose Django port
      - "8010:8000"
      # Expose Jupyter port (if needed)
      - "8810:8888"
